// ---------------------------------------------------------------------------
// routes.h - saved waypoint routes, and the page that drives them.
//
// A route is an ordered list of waypoints with a name. The navigator already
// knows how to follow one (navigator.h, NavMode); this module is where they
// are kept, made, and passed between players.
//
// Two files sit next to the game:
//
//   farever-routes.txt         generated by tools/gen-routes.mjs out of the
//                              game's own world data - every chest in a zone,
//                              every secret orb, the ore and herb circuits.
//                              Regenerated after a patch; not yours to edit.
//   farever-routes-custom.txt  yours. Routes you record by dropping waypoints,
//                              and routes you import from someone else, land
//                              here and survive regeneration.
//
// Sharing is a single line of text. "Copy" puts an FMKR1: code on the
// clipboard, "Import" reads one back off it - so a route travels through
// Discord, a forum post or a text file without anyone agreeing on where files
// live. The code is base64 over the same plain text the files use, so it
// stays inspectable rather than becoming an opaque blob.
// ---------------------------------------------------------------------------
#pragma once

#include <string>
#include <vector>

#include "input.h"
#include "navigator.h"

namespace fmk {

struct Route {
    std::string name;
    std::string zone;             // free text, shown as a subtitle
    NavMode mode = kNavRoute;
    bool custom = false;          // came from the custom file, so it can be
                                  // deleted from inside the game
    std::vector<NavTarget> points;
};

// Worker thread, after nav_init(). Loads both files; missing files are not an
// error, they just mean no routes yet.
void routes_init();

// Worker thread, about once a second: writes the custom file when it changed.
void routes_tick();

// Render thread: the Routes page. Draws inside the content band the atlas
// window hands it and owns everything in there, including its own scrolling.
void routes_draw(const InputState& in, bool clicked, float x, float y, float w,
                 float h);

// How many routes are loaded, for the tab label.
int routes_count();

}  // namespace fmk
