// GENERATED by tools/gen-offsets.mjs - do not edit.
//
// Field offsets read out of Farever's HashLink bytecode type table and
// laid out with HashLink's own hl_get_obj_rt algorithm. Regenerate after a
// game patch:  node tools/gen-offsets.mjs
#pragma once

#include <stdint.h>

// SHA-256 of the hlboot.dat these offsets came from. The reader must refuse
// to walk pointers when the running game does not match.
#define FMK_BUILD_SHA256 "90b9874167f453aa5e8762ebfef2c6890c6a06d2b6e314608c1e9b52a4234c65"

namespace fmk {
namespace off {

// ent.Hero  (sizeof=1672, extends ent.Unit)
namespace ent_Hero {
    constexpr uint32_t SIZEOF = 1672;
    constexpr uint32_t player = 0x4c0;  // OBJ : st.Player
    constexpr uint32_t lockedTarget = 0x4d8;  // I64
    constexpr uint32_t autoTarget = 0x4e0;  // I64
    constexpr uint32_t weaponInHand = 0x540;  // OBJ : st.item.Weapon
    constexpr uint32_t loadout = 0x4d0;  // OBJ : st.Loadout
    constexpr uint32_t specialization = 0x4c8;  // OBJ : st.player.HeroSpecialization
    constexpr uint32_t name = 0x500;  // OBJ : String
    constexpr uint32_t _level = 0x3e0;  // I32 : inherited ent.Unit level
}  // namespace ent_Hero

// st.player.HeroSpecialization  (sizeof=192, extends st.DBBaseState)
namespace st_player_HeroSpecialization {
    constexpr uint32_t SIZEOF = 192;
    constexpr uint32_t jobs = 0x78;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t talents = 0x80;  // OBJ : hxbit.MapData
    constexpr uint32_t skillMasteries = 0x88;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_player_HeroSpecialization

// hxbit.ObjProxy_3327ea72931d811ba796c031db6ffed0  (sizeof=80)
namespace hxbit_ObjProxy_3327ea72931d811ba796c031db6ffed0 {
    constexpr uint32_t SIZEOF = 80;
    constexpr uint32_t job = 0x20;  // OBJ : String
    constexpr uint32_t level = 0x38;  // I32
    constexpr uint32_t knowledge = 0x28;  // F64
    constexpr uint32_t learnedCrafts = 0x30;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t completedCrafts = 0x18;  // OBJ : hxbit.MapData
}  // namespace hxbit_ObjProxy_3327ea72931d811ba796c031db6ffed0

// ent.Unit  (sizeof=1216, extends ent.GameObject)
namespace ent_Unit {
    constexpr uint32_t SIZEOF = 1216;
    constexpr uint32_t isInCombat = 0x2b0;  // BOOL
    constexpr uint32_t instigatedStatuses = 0x1f8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t skin = 0x3e4;  // I32
    constexpr uint32_t kind = 0x258;  // OBJ : String
}  // namespace ent_Unit

// ent.GameObject  (sizeof=600, extends ent.Entity)
namespace ent_GameObject {
    constexpr uint32_t SIZEOF = 600;
    constexpr uint32_t posx = 0xb0;  // F64
    constexpr uint32_t posy = 0xb8;  // F64
    constexpr uint32_t posz = 0xc0;  // F64
    constexpr uint32_t rotationZ = 0xc8;  // F64
}  // namespace ent_GameObject

// GameApp  (sizeof=320, extends App)
namespace GameApp {
    constexpr uint32_t SIZEOF = 320;
    constexpr uint32_t gameCamera = 0xb0;  // OBJ : client.GameCamera
    constexpr uint32_t camera = 0xa8;  // OBJ : client.BaseCamera
    constexpr uint32_t hero = 0xd0;  // OBJ : ent.Hero
    constexpr uint32_t world = 0x98;  // OBJ : world.World
    constexpr uint32_t gui = 0xa0;  // OBJ : ui.GameUI
    constexpr uint32_t loadingState = 0xf8;  // I32
    constexpr uint32_t layer = 0xe0;  // OBJ : st.GameLayer
}  // namespace GameApp

// ui.GameUI  (sizeof=296, extends ui.BaseUI)
namespace ui_GameUI {
    constexpr uint32_t SIZEOF = 296;
    constexpr uint32_t windows = 0x90;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t root = 0x18;  // OBJ : ui.BaseUIRoot
    constexpr uint32_t s2d = 0x8;  // OBJ : h2d.Scene
    constexpr uint32_t gameRoot = 0x110;  // OBJ : ui.GameUiRoot
}  // namespace ui_GameUI

// ui.GameUiRoot  (sizeof=1112, extends ui.UIElement)
namespace ui_GameUiRoot {
    constexpr uint32_t SIZEOF = 1112;
    constexpr uint32_t hud = 0x448;  // OBJ : ui.Hud
}  // namespace ui_GameUiRoot

// ui.Hud  (sizeof=1408, extends ui.UIElement)
namespace ui_Hud {
    constexpr uint32_t SIZEOF = 1408;
    constexpr uint32_t chat = 0x498;  // OBJ : ui.hud.ChatBox
}  // namespace ui_Hud

// h2d.Flow  (sizeof=512, extends h2d.Object)
namespace h2d_Flow {
    constexpr uint32_t SIZEOF = 512;
    constexpr uint32_t calculatedWidth = 0x1a0;  // F64
    constexpr uint32_t calculatedHeight = 0x1a8;  // F64
    constexpr uint32_t contentWidth = 0x1b0;  // F64
    constexpr uint32_t contentHeight = 0x1b8;  // F64
}  // namespace h2d_Flow

// h2d.Scene  (sizeof=360, extends h2d.Layers)
namespace h2d_Scene {
    constexpr uint32_t SIZEOF = 360;
    constexpr uint32_t width = 0xbc;  // I32
    constexpr uint32_t height = 0xc0;  // I32
    constexpr uint32_t events = 0x140;  // OBJ : hxd.SceneEvents
}  // namespace h2d_Scene

// ui.win.MapWindow  (sizeof=1808, extends ui.win.TitleWindow)
namespace ui_win_MapWindow {
    constexpr uint32_t SIZEOF = 1808;
    constexpr uint32_t mouseCursor = 0x530;  // OBJ : ui.win.map.MapMarker
    constexpr uint32_t nearClickableMarker = 0x568;  // OBJ : ui.win.map.MapMarker
    constexpr uint32_t pinMarkers = 0x570;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t markers = 0x548;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t visible = 0x50;  // BOOL
    constexpr uint32_t parent = 0x18;  // OBJ : h2d.Object
    constexpr uint32_t zoom = 0x500;  // F64
}  // namespace ui_win_MapWindow

// ui.win.map.MapMarker  (sizeof=1120, extends ui.UIElement)
namespace ui_win_map_MapMarker {
    constexpr uint32_t SIZEOF = 1120;
    constexpr uint32_t worldPos = 0x448;  // OBJ : h3d.VectorImpl
    constexpr uint32_t visible = 0x50;  // BOOL
    constexpr uint32_t name = 0x20;  // OBJ : String
    constexpr uint32_t absX = 0x98;  // F64
    constexpr uint32_t absY = 0xa0;  // F64
}  // namespace ui_win_map_MapMarker

// ui.win.map.TextMarker  (sizeof=1136, extends ui.win.map.MapMarker)
namespace ui_win_map_TextMarker {
    constexpr uint32_t SIZEOF = 1136;
    constexpr uint32_t desc = 0x468;  // OBJ : String
}  // namespace ui_win_map_TextMarker

// $App  (sizeof=88, extends hl.Class)
namespace _App {
    constexpr uint32_t SIZEOF = 88;
    constexpr uint32_t inst = 0x30;  // OBJ : App
}  // namespace _App

// client.BaseCamera  (sizeof=304, extends h3d.scene.Object)
namespace client_BaseCamera {
    constexpr uint32_t SIZEOF = 304;
    constexpr uint32_t direction = 0xd0;  // F64
    constexpr uint32_t curDirection = 0x100;  // F64
    constexpr uint32_t pitch = 0xd8;  // F64
    constexpr uint32_t curPitch = 0xf8;  // F64
    constexpr uint32_t curDistance = 0x108;  // F64
    constexpr uint32_t enabled = 0xe8;  // BOOL
    constexpr uint32_t scene = 0x118;  // OBJ : h3d.scene.Scene
}  // namespace client_BaseCamera

// h3d.scene.Scene  (sizeof=288, extends h3d.scene.Object)
namespace h3d_scene_Scene {
    constexpr uint32_t SIZEOF = 288;
    constexpr uint32_t camera = 0xa0;  // OBJ : h3d.Camera
}  // namespace h3d_scene_Scene

// h3d.Camera  (sizeof=204)
namespace h3d_Camera {
    constexpr uint32_t SIZEOF = 204;
    constexpr uint32_t pos = 0x58;  // OBJ : h3d.VectorImpl
    constexpr uint32_t target = 0x68;  // OBJ : h3d.VectorImpl
}  // namespace h3d_Camera

// h3d.VectorImpl  (sizeof=32)
namespace h3d_VectorImpl {
    constexpr uint32_t SIZEOF = 32;
    constexpr uint32_t x = 0x8;  // F64
    constexpr uint32_t y = 0x10;  // F64
    constexpr uint32_t z = 0x18;  // F64
}  // namespace h3d_VectorImpl

// st.Player  (sizeof=385, extends st.State)
namespace st_Player {
    constexpr uint32_t SIZEOF = 385;
    constexpr uint32_t accountProgress = 0xe0;  // OBJ : st.player.AccountProgress
    constexpr uint32_t progress = 0xf0;  // OBJ : st.player.Progress
    constexpr uint32_t name = 0xc0;  // OBJ : String
    constexpr uint32_t heroData = 0xe8;  // OBJ : st.player.HeroData
    constexpr uint32_t activityCtx = 0x128;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t chatClient = 0x148;  // OBJ : st.player.ChatClient
    constexpr uint32_t isMe = 0x138;  // BOOL
    constexpr uint32_t group = 0x100;  // OBJ : st.Group
    constexpr uint32_t hero = 0x130;  // OBJ : ent.Hero
    constexpr uint32_t uid = 0xb8;  // OBJ : String
    constexpr uint32_t __uid = 0x20;  // I64
    constexpr uint32_t removed = 0x8;  // BOOL
}  // namespace st_Player

// st.player.HeroData  (sizeof=360, extends st.DBState)
namespace st_player_HeroData {
    constexpr uint32_t __uid = 0x20;  // I64
    constexpr uint32_t SIZEOF = 360;
    constexpr uint32_t level = 0xb0;  // I32
    constexpr uint32_t exp = 0xb4;  // I32
    constexpr uint32_t currencies = 0x110;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t inventory = 0x100;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t name = 0xa0;  // OBJ : String
    constexpr uint32_t worldLootLog = 0x128;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t activityProgress = 0x138;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t kind = 0xa8;  // OBJ : String
}  // namespace st_player_HeroData

// st.player.Progress  (sizeof=232, extends st.DBBaseState)
namespace st_player_Progress {
    constexpr uint32_t SIZEOF = 232;
    constexpr uint32_t counters = 0x80;  // OBJ : haxe.ds.StringMap
    constexpr uint32_t unitsProgress = 0xa0;  // OBJ : hxbit.MapData
    constexpr uint32_t itemProgress = 0xa8;  // OBJ : hxbit.MapData
    constexpr uint32_t zones = 0xc0;  // OBJ : hxbit.MapData
    constexpr uint32_t achievements = 0xc8;  // OBJ : hxbit.MapData
    constexpr uint32_t pets = 0xd0;  // OBJ : hxbit.MapData
    constexpr uint32_t skillMasteriesLearnt = 0xd8;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t activities = 0x88;  // OBJ : hxbit.MapData
    constexpr uint32_t elements = 0x90;  // OBJ : hxbit.MapData
    constexpr uint32_t npcs = 0x98;  // OBJ : hxbit.MapData
    constexpr uint32_t weaponProgress = 0xb0;  // OBJ : hxbit.MapData
}  // namespace st_player_Progress

// hxbit.MapData  (sizeof=48, extends hxbit.BaseProxy)
namespace hxbit_MapData {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t map = 0x28;  // VIRTUAL
}  // namespace hxbit_MapData

// hxbit.ObjProxy_OkillCount_Int_rank_Int  (sizeof=48)
namespace hxbit_ObjProxy_OkillCount_Int_rank_Int {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t killCount = 0x14;  // I32
    constexpr uint32_t rank = 0x18;  // I32
}  // namespace hxbit_ObjProxy_OkillCount_Int_rank_Int

// hxbit.ObjProxy_Ocompleted_Float  (sizeof=48)
namespace hxbit_ObjProxy_Ocompleted_Float {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t completed = 0x18;  // F64
}  // namespace hxbit_ObjProxy_Ocompleted_Float

// hxbit.ObjProxy_OcompletedOnce_Bool_lastCompletion_Float  (sizeof=48)
namespace hxbit_ObjProxy_OcompletedOnce_Bool_lastCompletion_Float {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t completedOnce = 0x14;  // BOOL
    constexpr uint32_t lastCompletion = 0x18;  // F64
}  // namespace hxbit_ObjProxy_OcompletedOnce_Bool_lastCompletion_Float

// hxbit.ObjProxy_ad383d83eed03d0e5475cee203565222  (sizeof=56)
namespace hxbit_ObjProxy_ad383d83eed03d0e5475cee203565222 {
    constexpr uint32_t SIZEOF = 56;
    constexpr uint32_t goalsMap = 0x20;  // OBJ : hxbit.MapData
    constexpr uint32_t dialog = 0x18;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t bit = 0x10;  // I32
}  // namespace hxbit_ObjProxy_ad383d83eed03d0e5475cee203565222

// hxbit.ObjProxy_Oexp_Int  (sizeof=40)
namespace hxbit_ObjProxy_Oexp_Int {
    constexpr uint32_t SIZEOF = 40;
    constexpr uint32_t exp = 0x14;  // I32
}  // namespace hxbit_ObjProxy_Oexp_Int

// haxe.ds.StringMap  (sizeof=24)
namespace haxe_ds_StringMap {
    constexpr uint32_t SIZEOF = 24;
    constexpr uint32_t h = 0x8;  // ABSTRACT : hl_bytes_map
}  // namespace haxe_ds_StringMap

// st.player.AccountProgress  (sizeof=208, extends st.DBState)
namespace st_player_AccountProgress {
    constexpr uint32_t SIZEOF = 208;
    constexpr uint32_t collection = 0xa8;  // OBJ : st.player.Collection
    constexpr uint32_t bank = 0xb8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankEquipment = 0xc0;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t bankNbSlots = 0xc8;  // I32
}  // namespace st_player_AccountProgress

// st.player.Collection  (sizeof=168, extends st.DBBaseState)
namespace st_player_Collection {
    constexpr uint32_t SIZEOF = 168;
    constexpr uint32_t mounts = 0x80;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gliders = 0x78;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t pets = 0xa0;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t gears = 0x98;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t toys = 0x88;  // OBJ : hxbit.ArrayProxyData
    constexpr uint32_t emotes = 0x90;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_player_Collection

// hxbit.ArrayProxyData  (sizeof=48, extends hxbit.BaseProxy)
namespace hxbit_ArrayProxyData {
    constexpr uint32_t SIZEOF = 48;
    constexpr uint32_t array = 0x28;  // OBJ : hl.types.ArrayDyn
}  // namespace hxbit_ArrayProxyData

// st.Loadout  (sizeof=208, extends st.DBBaseState)
namespace st_Loadout {
    constexpr uint32_t SIZEOF = 208;
    constexpr uint32_t equipment = 0x78;  // OBJ : st.Equipment
    constexpr uint32_t appearance = 0x80;  // OBJ : st.Inventory
    constexpr uint32_t inventory = 0x88;  // OBJ : st.Inventory
}  // namespace st_Loadout

// st.Inventory  (sizeof=160, extends st.DBBaseState)
namespace st_Inventory {
    constexpr uint32_t SIZEOF = 160;
    constexpr uint32_t content = 0x78;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t baseSize = 0x80;  // I32
    constexpr uint32_t addSize = 0x84;  // I32
}  // namespace st_Inventory

// st.item.Gear  (sizeof=160, extends st.Item)
namespace st_item_Gear {
    constexpr uint32_t SIZEOF = 160;
    constexpr uint32_t kind = 0x70;  // OBJ : String
    constexpr uint32_t level = 0x90;  // I32
    constexpr uint32_t upgradeLevel = 0x94;  // I32
    constexpr uint32_t slots = 0x98;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_item_Gear

// st.item.Weapon  (sizeof=176, extends st.item.Gear)
namespace st_item_Weapon {
    constexpr uint32_t SIZEOF = 176;
    constexpr uint32_t rarity = 0xa0;  // OBJ : String
}  // namespace st_item_Weapon

// hl.types.ArrayDyn  (sizeof=17, extends hl.types.ArrayAccess)
namespace hl_types_ArrayDyn {
    constexpr uint32_t SIZEOF = 17;
    constexpr uint32_t array = 0x8;  // OBJ : hl.types.ArrayBase
}  // namespace hl_types_ArrayDyn

// hl.types.ArrayObj  (sizeof=24, extends hl.types.ArrayBase)
namespace hl_types_ArrayObj {
    constexpr uint32_t SIZEOF = 24;
    constexpr uint32_t length = 0x8;  // I32
    constexpr uint32_t array = 0x10;  // ARRAY
}  // namespace hl_types_ArrayObj

// hl.types.ArrayBase  (sizeof=12, extends hl.types.ArrayAccess)
namespace hl_types_ArrayBase {
    constexpr uint32_t SIZEOF = 12;
    constexpr uint32_t length = 0x8;  // I32
}  // namespace hl_types_ArrayBase

// String  (sizeof=20)
namespace String {
    constexpr uint32_t SIZEOF = 20;
    constexpr uint32_t bytes = 0x8;  // BYTES
    constexpr uint32_t length = 0x10;  // I32
}  // namespace String

// st.player.ChatClient  (sizeof=200, extends st.State)
namespace st_player_ChatClient {
    constexpr uint32_t SIZEOF = 200;
    constexpr uint32_t history = 0xb8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t player = 0xb0;  // OBJ : st.Player
    constexpr uint32_t chat = 0xc0;  // OBJ : st.ChatServer
}  // namespace st_player_ChatClient

// ui.hud.ChatBox  (sizeof=1160, extends ui.UIElement)
namespace ui_hud_ChatBox {
    constexpr uint32_t SIZEOF = 1160;
    constexpr uint32_t messages = 0x468;  // OBJ : ui.BaseElement
    constexpr uint32_t messageInput = 0x480;  // OBJ : ui.comp.InputBox
    constexpr uint32_t channelDropdown = 0x478;  // OBJ : ui.comp.Dropdown
    constexpr uint32_t chatClient = 0x448;  // OBJ : st.player.ChatClient
    constexpr uint32_t messageIndex = 0x450;  // I32
    constexpr uint32_t footer = 0x470;  // OBJ : ui.BaseElement
}  // namespace ui_hud_ChatBox

// ui.hud.ChatBoxLine  (sizeof=1104, extends ui.UIElement)
namespace ui_hud_ChatBoxLine {
    constexpr uint32_t SIZEOF = 1104;
    constexpr uint32_t msgText = 0x448;  // OBJ : ui.comp.FmtText
}  // namespace ui_hud_ChatBoxLine

// ui.hud.ChatBoxMessage  (sizeof=1112, extends ui.hud.ChatBoxLine)
namespace ui_hud_ChatBoxMessage {
    constexpr uint32_t SIZEOF = 1112;
    constexpr uint32_t message = 0x450;  // VIRTUAL
}  // namespace ui_hud_ChatBoxMessage

// ui.comp.InputBox  (sizeof=1128, extends ui.UIElement)
namespace ui_comp_InputBox {
    constexpr uint32_t SIZEOF = 1128;
    constexpr uint32_t input = 0x458;  // OBJ : ui.comp.FmtTextInput
    constexpr uint32_t hintText = 0x448;  // OBJ : String
}  // namespace ui_comp_InputBox

// h2d.TextInput  (sizeof=712, extends h2d.Text)
namespace h2d_TextInput {
    constexpr uint32_t SIZEOF = 712;
    constexpr uint32_t interactive = 0x1e0;  // OBJ : h2d.Interactive
    constexpr uint32_t cursorIndex = 0x188;  // I32
}  // namespace h2d_TextInput

// h2d.Text  (sizeof=392, extends h2d.Drawable)
namespace h2d_Text {
    constexpr uint32_t SIZEOF = 392;
    constexpr uint32_t text = 0xe0;  // OBJ : String
}  // namespace h2d_Text

// hxd.SceneEvents  (sizeof=152)
namespace hxd_SceneEvents {
    constexpr uint32_t SIZEOF = 152;
    constexpr uint32_t currentFocus = 0x30;  // VIRTUAL
}  // namespace hxd_SceneEvents

// h2d.Object  (sizeof=176)
namespace h2d_Object {
    constexpr uint32_t SIZEOF = 176;
    constexpr uint32_t absX = 0x98;  // F64
    constexpr uint32_t absY = 0xa0;  // F64
    constexpr uint32_t visible = 0x50;  // BOOL
    constexpr uint32_t parent = 0x18;  // OBJ : h2d.Object
    constexpr uint32_t children = 0x8;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t alpha = 0x58;  // F64
}  // namespace h2d_Object

// ui.BaseUI  (sizeof=264)
namespace ui_BaseUI {
    constexpr uint32_t SIZEOF = 264;
    constexpr uint32_t elements = 0x70;  // OBJ : hl.types.ArrayObj
    constexpr uint32_t console = 0x60;  // OBJ : ui.Console
}  // namespace ui_BaseUI

// h2d.Console  (sizeof=281, extends h2d.Object)
namespace h2d_Console {
    constexpr uint32_t SIZEOF = 281;
    constexpr uint32_t bg = 0xb8;  // OBJ : h2d.Bitmap
    constexpr uint32_t tf = 0xc0;  // OBJ : h2d.TextInput
}  // namespace h2d_Console

// st.Group  (sizeof=216, extends st.State)
namespace st_Group {
    constexpr uint32_t SIZEOF = 216;
    constexpr uint32_t players = 0xb8;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_Group

// st.GameLayer  (sizeof=400, extends st.State)
namespace st_GameLayer {
    constexpr uint32_t SIZEOF = 400;
    constexpr uint32_t players = 0xe0;  // OBJ : hxbit.ArrayProxyData
}  // namespace st_GameLayer

}  // namespace off
}  // namespace fmk
